<a href="https://colab.research.google.com/github/anhtrannguyenvan/AIO_2024_Exercise/blob/feature%2Fmodule2%2Fweek2/Week2_Module2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import library
import numpy as np
def compute_vector_length(vector):
    vector_length = np.sqrt(np.sum(vector**2))
    return vector_length

In [2]:
def compute_dot_product(vector1, vector2):
    dot_product = np.dot(vector1, vector2)
    return dot_product

In [3]:
def matrix_multi_vector(matrix, vector):
    result = np.dot(matrix, vector)
    return result

In [4]:
import numpy as np
def inverse_matrix(matrix):
    inverse_matrix = np.linalg.inv(matrix)
    return inverse_matrix

In [5]:
#Example
a = np.array([[0.9, 0.2],
              [0.1, 0.8]])
a_inv = inverse_matrix(a)
print(a_inv)


[[ 1.14285714 -0.28571429]
 [-0.14285714  1.28571429]]


In [6]:
def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

In [7]:
a = np.array([[0.9, 0.2],
              [0.1, 0.8]])
a_eigenvalues, a_eigenvectors = compute_eigenvalues_eigenvectors(a)
print(a_eigenvalues)
print(a_eigenvectors)

[1.  0.7]
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [46]:
def compute_cosine(x, y):
    # Tính tích vô hướng của x và y
    dot_product = np.dot(x, y)
    # Tính chuẩn Euclidean của x và y
    norm_x = np.linalg.norm(x)
    norm_y = np.linalg.norm(y)
    # Tính độ tương đồng cosine
    cosine_similarity = dot_product / (norm_x * norm_y)
    return cosine_similarity

In [11]:
#Background subtraction
import numpy as np
from google.colab.patches import cv2_imshow
import cv2

bg1_image = cv2.imread('/content/GreenBackground.png',1)
bg1_image = cv2.resize(bg1_image, (678, 381))

ob_image = cv2.imread('/content/Object.png',1)
ob_image = cv2.resize(ob_image, (678, 381))


bg2_image = cv2.imread('/content/NewBackground.jpg',1)
bg2_image = cv2.resize(bg2_image, (678, 381))

In [12]:
#Build compute different
def compute_difference(bg_img, input_img):
  difference = cv2.absdiff(bg_img, input_img)
  return difference


In [14]:
#build ham compute_binary_mask()

def compute_binary_mask(difference_single_channel):
  threshold = 20
  _, binary_mask = cv2.threshold(difference_single_channel, threshold, 255, cv2.THRESH_BINARY)
  return binary_mask

In [ ]:
binary_mask = compute_binary_mask(difference_single_channel)
cv2_imshow(binary_mask)

In [17]:
#build def replace background
def replace_background(bg1_image , bg2_image , ob_image):
  difference_single_channel = compute_difference(bg1_image, ob_image)
  binary_mask = compute_binary_mask(difference_single_channel)
  output = np.where(binary_mask == 255, bg2_image, ob_image)
  return output



**MUTIPLE CHOICE**



In [18]:
#Cau1
vector = np.array([-2,4,9,21])
result = compute_vector_length(vector)
print(round(result, 2))

23.28


In [19]:
v1 = np.array([0,1,-1,2])
v2 = np.array([2,5,1,0])
result = compute_dot_product(v1, v2)
print(round(result, 2))

4


In [20]:
#Cau3:
x = np.array([[1,2],
             [3,4]])
k = np.array([1,2])
print(x.dot(k))

[ 5 11]


In [21]:
#Cau4
x=np.array([[-1,2],
            [3,-4]])
k = np.array([1,2])
print(x@k)

[ 3 -5]


In [22]:
#Cau5
m = np.array([[ -1 , 1 , 1] , [0 , -4 , 9]])
v = np.array([0,2,1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


In [23]:
#Cau6
m1 = np.array([[0,1,2], [2,-3,1]])
m2 = np. array ([[1 , -3] ,[6 , 1] , [0 , -1]])
result = matrix_multi_vector(m1, m2)
print(result)

[[  6  -1]
 [-16 -10]]


In [25]:
#cau7
m1 = np.eye(3)
m2 = np.array([[1 , 1 , 1] ,[2 , 2 , 2] , [3 , 3 , 3]])
result = m1@m2
print(result)

[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [27]:
#Cau8
m1 = np.eye(2)
m1 = np.reshape(m1,(-1 ,4))[0]
m2 = np.array ([[1 , 1 , 1 , 1] ,[2 , 2 , 2 , 2] , [3 , 3 , 3 , 3] , [4 , 4 , 4 , 4]])
result = m1@m2
print(result)

[5. 5. 5. 5.]


In [31]:
#Cau9
m1 = np.array([[1 , 2] , [3 , 4]])
m1 = np.reshape(m1,(-1 ,4),"F")[0]
m2 = np.array ([[1 , 1 , 1 , 1] ,[2 , 2 , 2 , 2] , [3 , 3 , 3 , 3] , [4 , 4 , 4 , 4]])
result = m1@m2
print(result)

[29 29 29 29]


In [33]:
#Cau10
m1 = np.array([[-2,6],[8,-4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [34]:
#Cau11
matrix = np.array([[0.9,0.2],[0.1,0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [47]:
#Cau12
x = np.array([1,2,3,4])
y = np.array([1,0,3,0])
result = compute_cosine(x, y)
print(round(result,3))

0.577
