<a href="https://colab.research.google.com/github/anhtrannguyenvan/AIO_2024_Exercise/blob/feature%2Fmodule2%2Fweek1/Week1_Module2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.arange(0,10,1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
arr = np.ones((3,3))>0
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
arr = np.ones((3,3),dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
arr = np.full((3,3), fill_value=True, dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
arr = np.arange(0,10)
print(arr[arr%2==1])

[1 3 5 7 9]


In [9]:
arr = np.arange(0,10)
arr[arr%2==1]=-1
print(arr)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [10]:
#Cau5
arr = np.arange(0,10)
arr_2d = arr.reshape (2,-1)
print(arr_2d)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
#Cau6
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)
c = np.concatenate((arr1,arr2),axis=0)
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [13]:
#Cau7:
arr1 = np.arange(10).reshape(2,-1)
arr2 = np.repeat(1,10).reshape(2,-1)
c = np.concatenate((arr1,arr2),axis=1)
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [14]:
#CAU8:
arr = np.array([1,2,3])
print(np.repeat(arr,3))
print(np.tile(arr,3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [46]:
#Cau9
a = np.array([2,6,1,9,10,3,27])
index = np.where((a>=5)&(a<=10))
print(a[index])

[ 6  9 10]


In [16]:
#Cau10
def maxx(x,y):
  if x>=y:
    return x
  else:
    return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx,otypes=[float])
print(pair_max(a,b))

[6. 7. 9. 8. 9. 7. 5.]


In [17]:
a = np.array([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np.array([6 ,3 ,4 ,8 ,9 ,7 ,1])
print(np.where(a<b,b,a))

[6 7 9 8 9 7 5]


In [18]:
#Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 56.3MB/s]


In [23]:
#Cau12
import matplotlib.image as mpimg
from skimage.color import rgb2gray
img = mpimg.imread('/content/dog.jpeg')
gray_img_01 = 0.5 * (np.max(img, axis=2) + np.min(img, axis=2))
gray_img_01 [0 , 0]


102.5

In [24]:
#Cau13
gray_img_02 = np.mean(img, axis=2)
gray_img_02 [0 , 0]

107.66666666666667

In [26]:
#Cau14
gray_img_03 = 0.299 * img[:, :, 0] + 0.587 * img[:, :, 1] + 0.114 * img[:, :, 2]
gray_img_03 [0 , 0]

122.03399999999999

In [28]:
# Download data
!gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 15.7MB/s]


In [30]:
import pandas as pd

df = pd.read_csv('/content/advertising.csv')
data = df.to_numpy()

In [32]:
#Cau15
max_value = df['Sales'].max()
max_index = df['Sales'].idxmax()
print(max_value)
print(max_index)

27.0
175


In [33]:
#Cau16
avg_tv = df['TV'].mean()
print(avg_tv)

147.0425


In [34]:
#Cau17
count_sales_20_or_more = (df['Sales']>=20).sum()
print(count_sales_20_or_more)

40


In [35]:
#Cau18
avg_radio = df[df['Sales']>=15]['Radio'].mean()
print(avg_radio)

26.22293577981651


In [36]:
#Cau19
newspaper_data = data[:,2]
newspaper_mean = newspaper_data.mean()
newspaper_cond = (newspaper_data>newspaper_mean)

sales_data = data[:,3]
sales_cond = sales_data*newspaper_cond
sales_sum = np.sum(sales_cond)
print(sales_sum)


1405.1


In [40]:
#Cau20
sales_data = data[:,3]
sales_mean = np.mean(sales_data)
score_sales = np.where(
    sales_data<sales_mean,"Bad",np.where(sales_data>sales_mean,"Good","Average"))
score_sales[7:10]



array(['Bad', 'Bad', 'Good'], dtype='<U7')

In [44]:
#Cau21
sales_data = data[:,3]
sales_mean = np.mean(sales_data)
average_index = np.argmin(abs(sales_data-sales_mean))
sales_closet = sales_data[average_index]
sales_closet

15.2

In [45]:
sales_closet = np.where(
    sales_data<sales_mean,"Bad",np.where(sales_data>sales_mean,"Good","Average"))
sales_closet[7:10]

array(['Bad', 'Bad', 'Good'], dtype='<U7')